apiVersion: v1
kind: Endpoints
metadata:
  name: nodered-sensors
  labels:
    app: nodered-sensors  
subsets:
- addresses:
  - ip: 172.16.207.11
  ports:
  - name: web
    port: 1880
    protocol: TCP
