
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: nodered-sensors
spec:
  endpoints:
  - interval: 60s
    port: web
  selector:
    matchLabels:
      app: nodered-sensors