apiVersion: v1
kind: Service
metadata:
  name: nodered-sensors
  labels:
    app: nodered-sensors
spec:
  externalName: 172.16.207.11
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
  type: ExternalName
