apiVersion: v1
kind: Service
metadata:
  name: nodered-sensors
  labels:
    app: nodered-sensors
spec:
  selector: {}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
