
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: nodered-sensors
spec:
  selector:
    matchLabels:
      app: nodered-sensors
  endpoints:
  - port: web
    interval: 30s
